### ISSUE TITLE
Where can I find the dataset FEMNIST and the Amazon’s Book Reviews Dataset as the paper shows?

### ISSUE THREAD

**Issue by wizard1203** [adap/flower#1378]
### What is your question?

Thanks for your awesome frameworks!
I hope to conduct experiments of FEMNSIT and Amazon’s Book Reviews. 
Could you please indicate where can I get these datasets?

**Comment by adam-narozniak** [comment]
Hi, 
You can find FEMINST in this repo https://github.com/adap/flower/tree/main/baselines/flwr_baselines/publications/leaf/femnist or in the original paper repo https://github.com/TalwalkarLab/leaf. However, I don't recommend going into the LEAF code and creating the dataset their way because e.g. the images are stored in the JSON files, and adjusting your code to use them will be time-consuming. Our version has standard images and a CSV file with references regarding the writers' ids and labels.

Amazon’s Book Reviews: https://www.kaggle.com/datasets/mohamedbakhet/amazon-books-reviews
