### ISSUE TITLE
Server and client on flower framework

### ISSUE THREAD

**Issue by AlesaRLife** [adap/flower#1434]
### What is your question?

In the first round, can we make the server wait for all clients to connect it "to get initial model parameters" instead of gets initial model parameters from one of the connected clients.

**Comment by danieljanes** [comment]
Thanks for reaching out @AlesaRLife.

Could you give a bit more background, what would be the use case for this?

The server cannot wait for all clients since the server does not know how many clients there are in total. What we could do though is to add a parameter that tells the server to wait for *at least* n clients. Before we do so, it'd be good to understand the motivation for this feature request better.

**Comment by AlesaRLife** [comment]
thank you for replying @danieljanes 
I want this, so that I can collect the parameters for example weights from all the clients and see if there are common factors between them before go to the server in the first round.

**Comment by danieljanes** [comment]
@AlesaRLife could you perhaps do this using a custom strategy? Make the strategy wait for all the clients, collect what you need using `get_properties`, then start the actual training?

**Comment by WilliamLindskog** [comment]
Hi @AlesaRLife,

is this an issue that you are still encountering?

**Comment by WilliamLindskog** [comment]
Hi again, 

this can be implemented using a custom strategy. You could override the `initialize_parameters` method in a custom strategy to wait until the expected number of clients connect and then request initial parameters from each client. These parameters could be aggregated or selected as needed before proceeding. 

I will close this issue for now.
