### ISSUE TITLE
New Client Joining after a trigger

### ISSUE THREAD

**Issue by sallu08** [adap/flower#1485]
### What is your question?

Is there a possibility to make a client join only after certain condition has been met. For example i have 10 clients available and i want 11th client only to join after 20 Federated rounds? is it possible in flower?

**Comment by edogab33** [comment]
Defenitely possible:

In your strategy you have a configre_fit() method which is called before any client start training. The purpose of this is to sample clients for the next round and to send configurations to your workers.
The simpliest way is to modify your configure_fit() method in order to check if the round is less than 20 and if that's True, you can remove any client you want for the next round.

To be clearer, here's the FedAvg implementation with a simple addition that causes the server to always exclude one client from the next round.

```
# Sample clients
sample_size, min_num_clients = self.num_fit_clients(
  client_manager.num_available()
)
sample_size -= 1     # here you remove one client
clients = client_manager.sample(
  num_clients=sample_size, min_num_clients=min_num_clients
)
```

**Comment by WilliamLindskog** [comment]
Closing this issue as it seems to have been resolved.
