### ISSUE TITLE
How to create connection between Client and server between 2 machines

### ISSUE THREAD

**Issue by shashankc28** [adap/flower#1489]
### What is your question?

Hi I have created a server on an azure VM . I have exposed the 8080 port but not able to connect to the server through my pc. Are there any other ports that I need to expose or any configuration for seamless connection .  
Also I have tried installing flower server in my local docker instance . Not able to connect within local machine as well . Server port exposed and mapped with machine port.

**Comment by ashkan-pirmani** [comment]
Hi,

To run the server script, you should pass the private IP address with the assigned port to your script, and your client should connect to your virtual machine's public IP address(with the given port).

It would help if you also made your port accessible through settings of the networking of your VM (Inbound port rules); otherwise, your VM would reject the connection.

**Comment by WilliamLindskog** [comment]
Hi, 

here is an example of how to set up Flower using deployment engine: https://github.com/adap/flower/tree/main/examples/app-pytorch

This might also help: 
https://github.com/adap/flower/blob/0254c88eea143ee62a15f89d9d4e9f4182e1ed32/doc/source/how-to-enable-tls-connections.rst

Closing this issue.
