### ISSUE TITLE
How to set “”server_address” (IP) between Client and server in different networks device?(i.e., not in LAN)

### ISSUE THREAD

**Issue by KawhiHeisenberg631** [adap/flower#1507]
### What is your question?

 When I set the server and clients to be in a different network, i.e. not in LAN, the codes reported errors.
Server:
![image](https://user-images.githubusercontent.com/71743851/206414944-65d4fba6-c3d8-4ece-9eff-76bd19fa64fe.png)
Server IPv4 address: 10.69.70.247

Client:
![image](https://user-images.githubusercontent.com/71743851/206415312-afed0363-3187-4623-a395-f9bcc0c5c273.png)
Client IPv4 address: 10.188.141.42

**Comment by danieljanes** [comment]
@KawhiHeisenberg631 could you provide more details about the setup you're trying to run? What do you mean by "not in LAN"?

**Comment by XKingham** [comment]
> 
Maybe his  "Not in LAN" means they are not in the same LAN, like the laptop is in the "LAN1" but the raspberry pi is in the "LAN2".  They can't communicate with each other easily.

**Comment by adarsh-nl** [comment]
Is there a solution for this issue? 

**Description:**
I'm encountering a problem with the Flower framework when attempting to connect the server and clients on different networks. The connection either times out or fails to establish. Below are the details of the issue:

**Steps to Reproduce:**

Set up a Flower server on Network A.
Attempt to connect a client from Network B.
Observe the connection failure or timeout.

**Expected Behavior:**
The client should successfully connect to the server even when they are on different networks.

**Actual Behavior:**
The connection fails to establish, resulting in timeouts or other errors as mentioned in this issue.

But there is no issue when both the server and clients are connected to the same network A.

**Comment by WilliamLindskog** [comment]
Hi 

thanks for raising this. This can be done by using docker image and running superlink on one network and supernodes on other networks and connect using docker credentials and right server address. These examples might help you get started: https://github.com/adap/flower/tree/main/examples/app-pytorch
https://github.com/adap/flower/tree/main/examples/embedded-devices
https://github.com/adap/flower/tree/main/examples/flower-authentication
https://github.com/adap/flower/blob/main/doc/source/how-to-authenticate-supernodes.rst

Closing this for now.
