### ISSUE TITLE
Run simulation_pytorch example, there are some questions

### ISSUE THREAD

**Issue by xiaoToby** [adap/flower#3066]
### Describe the bug

When I ran the examples/simulation-pytorch/sim.py,
and I set the NUM_CLIENT=2
But I ran this on a balena container, there are 6 cpus,and 4g memory.
Look at the screenshot,
![image](https://github.com/adap/flower/assets/40045458/637c8b4d-60b6-4b3c-a010-f30a2d9c8de2)

I do not know the reasons, and someone could help me to figure it out?
And my guess is the resource-limit is the reason.

### Steps/Code to Reproduce

1

### Expected Results

1

### Actual Results

1

**Comment by jafermarq** [comment]
Hi @xiaoToby, I suspect the issue you are having is not enough memory in your belena container (as you point out). You can try raising the number of `num_cpus` you pass to `start_simulation` so fewer clients run in parallel. With the arguments you have you can see up to 6 clients will run in parallel (see how the log says 6 actors are created). Maybe try setting `num_cpus` to 3 or higher?. Another option is to reduce the batch size.

Also, i changed the label to "question" since it fits better the topic here discussed.

**Comment by xiaoToby** [comment]
I just tried the --num_cpus is 3,the result is same,nothing changes.

**Comment by xiaoToby** [comment]
I ran it on embedded devices, like rockpi 4b, i can not the check type name of device now.

**Comment by xiaoToby** [comment]
On the sim.py file, I set the NUM_CLIENT=2, so i do not think there are  6 clients will run in parallel

**Comment by jafermarq** [comment]
> I ran it on embedded devices, like rockpi 4b, i can not the check type name of device now.
If you are running on an embedded device, It's preferable not to use simulation. You could take a look at the [examples/embedded-devices](https://github.com/adap/flower/tree/main/examples/embedded-devices) which do run fine on devices like Raspberry Pi or NVIDIA Jetson.

**Comment by xiaoToby** [comment]
ok, i already tired it, and wait the result. Thank you @jafermarq

**Comment by WilliamLindskog** [comment]
Hi @xiaoToby 

Thank you for raising this. Are you still experiencing this issue?

**Comment by WilliamLindskog** [comment]
Closing this issue as it seems to have been resolved.
