### ISSUE TITLE
Run quickstart-tensorflow demo error

### ISSUE THREAD

**Issue by Klein920116** [adap/flower#3664]
### Describe the bug

Run [quickstart-tensorflow](https://github.com/adap/flower/tree/main/examples/quickstart-tensorflow) demo and error occurs on client side:ConnectionError: Couldn't reach 'cifar10' on the Hub (ConnectionError)

Do I need download data before running demo? or any solution for this?

### Steps/Code to Reproduce

code from [quickstart-tensorflow](https://github.com/adap/flower/tree/main/examples/quickstart-tensorflow)

### Expected Results

result from [quickstart-tensorflow](https://github.com/adap/flower/tree/main/examples/quickstart-tensorflow)

### Actual Results

ConnectionError: Couldn't reach 'cifar10' on the Hub (ConnectionError)

**Comment by WilliamLindskog** [comment]
Hi @Klein920116, 

Thanks for opening this issue. When running the quickstart example, are you connected to the internet or do you run it locally without any network connection? flwr-datasets pull datasets from huggingface.

**Comment by WilliamLindskog** [comment]
Hi again, 

if you are connected to the internet, you can pull the data from HuggingFace-Hub. Otherwise, you need to store the dataset locally before running Flower. If it is a standard dataset, there are formal ways of loading that type of dataset that can be found online. 

Closing this issue for now.
