### ISSUE TITLE
Vertical Federated Learning functionality

### ISSUE THREAD

**Issue by TanvirHundredOne** [adap/flower#3676]
### What is your question?

I am looking into Vertical Federated Learning examples. Simulation works with 

```
hist = fl.simulation.start_simulation(
    client_fn=client_fn,
    num_clients=3,
    config=fl.server.ServerConfig(num_rounds=1000),
    strategy=Strategy(label),
)
```
code base. But how does `start_simulation` method knows its a vertical fl, other than data composition for each client there seems to be no way for the simulator to know whether its vertical or not or am I missing something obvious?

TIA

**Comment by WilliamLindskog** [comment]
Hi

Thanks for raising this. 

In the updated [Flower VFL example](https://github.com/adap/flower/blob/main/examples/vertical-fl/vertical_fl/task.py), the distinction between Vertical and Horizontal Federated Learning lies in the data partitioning and the roles of the server and clients. In VFL, data are vertically partitioned so that each client holds unique subsets of features for the same dataset. For instance, one client may handle `{Cabin, Parch, Pclass}`, another `{Sex, Title}`, and so on. Clients process their respective feature subsets using a `ClientModel`, generating embeddings that are sent to the server.

The server, using a `ServerModel`, aggregates these embeddings, computes a global loss, and sends gradients back to clients for local updates. The custom Strategy on the server handles this coordination, ensuring embeddings and gradients align with the feature subsets each client holds. 

Closing this issue for now.
