### ISSUE TITLE
Sending a subset of model weights to the clients

### ISSUE THREAD

**Issue by giacomoverardo** [adap/flower#538]
Hi,

Is it possible to have different models at client and server? Specifically, I would like to use a large model at the server side and send a fraction of the weights for each layer to the clients. Do you have any advice on where to implement these features? Would it be possible by creating a new strategy?

Thanks,
Giacomo

**Comment by danieljanes** [comment]
Hi @giacomoverardo , exactly, it's possible through a custom strategy implementation.

In short, you'd only put the subset of weights you want to pass to the clients into the `List[np.ndarray]` returned by `Strategy.configure_fit` - if the subset changes every round then I'd suggest to add some data about which layers you're sending to the config dict.

On the client side you'd check the `config` dict to see which layers are contained in `parameters` and then update those layers on your local model.

Hope that helps, let me know if you need further details :)

**Comment by giacomoverardo** [comment]
Thank you! Would it also be possible to send different weights to different clients?

**Comment by danieljanes** [comment]
Yes absolutely.

The return type of `Strategy.configure_fit` is `List[Tuple[ClientProxy, FitIns]]` (`FitIns` hold both model `parameters` and a `config` dict). The way Flower interprets this is as follows:
- the list contains pairs of `ClientProxy` and `FitIns`
- each pair represents a "selected client", so Flower sends the `FitIns` object to that client
- if the list contains a certain `ClientProxy` object, the server will send `FitIns` to that client (if it doesn't, the server knows that this client wasn't selected during the current round)

Here comes the bit that gives you the flexibility you need:
- each pair contains both a `ClientProxy` object (representing one of the connected clients) and a `FitIns` object (the instructions that will be sent to that particular client)
- the `FitIns` object can be **completely different for each client**
- if you want one client to do 5 epochs, but another client to do 10 epochs, just change the `FitIns.config` dict for each respective client
- if you want to send one list of weights to one client, but another list of weights to another client, just change the `FitIns.parameters` object
- to tell the client which parameters are included in the list of weights, I'd recommend to add some values to the `config` dict

This even allows you to have completely different models on each client. Note that most of the built-in strategies (such as `FedAvg`) sample a random subset of connected clients and then send identical `FitIns` to each of them (because vanilla `FedAvg` does send the exact same weights and instructions to each client). But custom strategies can of course change this and send completely different weights/instructions to each selected client (same goes for evaluation).
