### ISSUE TITLE
Multiple Clients 

### ISSUE THREAD

**Issue by ChangxinBai** [adap/flower#563]
Hi Developing team,

I am very interested in using flower to do some experiments.
Through the tensor flow example, I can use two clients successfully. I am wonder whether the system support more than two clients. If yes, how to do it?

Is the system support vertical federated learning cases?

Thanks

**Comment by tanertopal** [comment]
Hi @ChangxinBai

I am happy to hear that you want to do experiments with Flower!
Coming from the TensorFlow Quickstart example you can actually just start more clients and it will just work.

The biggest experiments we have run with Flower included 10k+ simultaneously participating clients in a single round of training.

If you like to have more fine grained control on the training you can either create your own strategy or e.g. configure the default strategy `FedAvg` to your requirements.
I would recommend you to make the following changes to the `server.py` file.  

```python
import flwr as fl
from flwr.server.strategy import FedAvg

# Start Flower server for three rounds of federated learning
if __name__ == "__main__":
    # FedAvg is the default strategy used when you start the server without a custom strategy
    strategy = FedAvg(
        # Minimum number of connected clients before sampling e.g. 10
        min_available_clients=10,

        # Fraction of clients which should participate in each round
        fraction_fit=0.3 
    )
    fl.server.start_server("0.0.0.0:8080", config={"num_rounds": 3})
```

After this change the server will wait until at least 10 clients are connected before it starts to sample. You can naturally increase that number. 

In regards to your question about vertical federated learning. We don't have any example for that yet but you can realise most cases of federated learning with Flower when you implement your own custom strategy. You can always use the [FedAvg strategy](https://github.com/adap/flower/blob/main/src/py/flwr/server/strategy/fedavg.py) as a boilerplate and start from there.

Does this answer your question?

**Comment by ChangxinBai** [comment]
Hi @tanertopal,
Thanks for your quick reply. All answered my questions.
I am looking forward to your next milestone.
Best

**Comment by 96Farhan** [comment]
Hi @tanertopal!. Thanks for information about increasing clients, it help me. But one more issue I am facing is that whether I start with 2/5/10 or any number of clients, server manipulate only 2 clients at a time and ends up with running number of rounds w.r.t 2 clients only. For example if I start with 5 clients with 3 number of rounds, ideally(if I am not wrong) it should have to execute 3 rounds for each client individually(should ended up running total 15 iterations for both train/test), but it was only ended up by running 6 iteration randomly for 5 clients, means equal to iteration of 2 clients not 5 clients. Moreover in server logs only 2 clients are initiating simultaneously instead of 5, with statement " strategy sampled 2 clients (out of 5)".
I am attaching screenshots below with 5 clients and 3 number of rounds. You can clearly see in these screenshots that only 6 iterations for training and 11 iterations for test was run randomly for 5 clients instead of 15 iterations(3 for both train/test per client smoothly).
In addition to that for some client as in my case for client4 training iteration was not run only test iteration was executed.
As per my understanding about flower in my case, it should have to run 3 iterations(equal to number of rounds), for both train and test per client.
Please let me know if i have to configure or add something.
Thanks!
![Screenshot (121)](https://user-images.githubusercontent.com/51117866/129459853-448270a1-7d89-4369-ba19-eef220e60ff5.png)
![Screenshot (122)](https://user-images.githubusercontent.com/51117866/129459861-913a2eb2-10b7-47fc-b57f-ab3b92aef8c1.png)
![Screenshot (123)](https://user-images.githubusercontent.com/51117866/129459863-a075fd10-2e4e-4fc6-90a3-2e993ed70cbd.png)
![Screenshot (124)](https://user-images.githubusercontent.com/51117866/129459866-92cfb9ba-1f8e-4e80-865a-5799a870e10c.png)
![Screenshot (125)](https://user-images.githubusercontent.com/51117866/129459867-bd460787-47ad-4346-a82a-d31b7241c08d.png)
![Screenshot (126)](https://user-images.githubusercontent.com/51117866/129459870-2173c89c-3510-425a-8a50-92a188498189.png)

**Comment by danieljanes** [comment]
Hi @96Farhan , the behavior you describe is correct (it's the default behavior of the default strategy). To customize it, you need to pass your own strategy instance to `start_server` and set `fraction_fit` to `1.0` (i.e. select all connected clients for training): https://flower.dev/docs/strategies.html

The server in `advanced_tensorflow` example might be helpful as well: https://github.com/adap/flower/blob/main/examples/advanced_tensorflow/server.py
