### ISSUE TITLE
Using results returned from client's fit

### ISSUE THREAD

**Issue by cozek** [adap/flower#712]
I want to save the results returned to the server by the client's fit method and save them. 
I am not sure how I am supposed to access the results in the server script.

The example in https://flower.dev/docs/saving-progress.html#aggregate-custom-evaluation-results only covers results from the clients evaluate function but does not show results from the client's fit function.

In the [advanced_tensorflow](https://github.com/adap/flower/blob/main/examples/advanced_tensorflow/client.py) example, the client's `fit` method is returning some results to the server, but the `server.py` is not using the these results anywhere. 

I could also do this if there was a way to access all the returned accuracies and results from the clients after the fl is finished.

is there an api reference of the returned result object ?

**Comment by danieljanes** [comment]
Hi @cozek , thanks for the questions. What you want to do isn't properly documented yet (and there will be built-in improvements in future releases), but you could do it in the same way as it's done in the docs you linked above. The only difference is that you'd override `aggregate_fit` instead of `aggregate_evaluate`:

```python
class SaveCustomFitMetricStrategy(fl.server.strategy.FedAvg):
    def aggregate_fit(
        self,
        rnd: int,
        results: List[Tuple[ClientProxy, FitRes]],
        failures: List[BaseException],
    ) -> Optional[Weights]:
        """Aggregate evaluation losses using weighted average."""
        if not results:
            return None

        # Save results
        for _, fit_res in results:
            fit_metrics = fit_res.metrics
            print("TODO: save individual results here", fit_metrics)

        # Call aggregate_fit from base class (FedAvg)
        return super().aggregate_fit(rnd, results, failures)
```

The `results` object is a list of tuples (pairs of `(ClientProxy, FitRes)`), the code example above shows how to get the dictionary returned by `Client.fit` from `FitRes`. The `flwr.common.typing` module contains many type definitions (for future reference):

https://github.com/adap/flower/blob/main/src/py/flwr/common/typing.py

**Comment by cozek** [comment]
@danieljanes Thanks for the code example and quick reply. This solves my use case for now.
