### ISSUE TITLE
Migrate mypy configuration to pyproject.toml

### ISSUE THREAD

**Issue by danieljanes** [adap/flower#762]
Parts of our mypy configuration live in `mypy.ini`. Support for configuration via `pyproject.toml` was recently added to mypy (https://mypy.readthedocs.io/en/stable/config_file.html#using-a-pyproject-toml-file), so we should migrate our configuration to follow a consistent approach over all Python tooling

**Comment by architjen** [comment]
Hi @danieljanes, I'm looking for my first contribution, can I take this issue? 
Also, could you brief me about the issue a little bit?

**Comment by danieljanes** [comment]
Hi @architjen , great to hear! Absolutely, feel free to take the issue. The general idea is to replicate the mypy config (that we currently have in mypy.ini) using pyproject.toml (and then get rid of mypy.ini altogether). Do you have any specific questions? Happy to provide more details

**Comment by architjen** [comment]
Ok, I'm on it! 
I'll get back to you if I have any questions.

**Comment by architjen** [comment]
Hi @danieljanes I'm trying to wrap my head around the issue rather than just solving it, correct me if I'm wrong, also, any additional remarks/suggestions from you would be much appreciated 

The idea here is: Instead of using `mypy.ini` it's preferable to use `myproject.toml` (according to PEP 518) so that tools like pip can read what tools are specified in `myproject.toml` install them to a virtual env to build our project.  

For solving the issue: We simply migrate the content from the `mypy.ini` file located at the root of the repo to the `myproject.toml` file located at the repo by converting it into the desired format given in mypy docs, and then removing the file `mypy.ini` from the repo. 

Sorry if part of my comment seems like a repetition from above.

**Comment by ronnie-llamado** [comment]
@architjen Is there an update on this? I have the changes on a local branch queued up for a PR if you decide to pass on this one. 

If I can offer a quick remark, try not to overthink it - it sounds like you have the idea.

**Comment by tanertopal** [comment]
@architjen thank you for your contribution. This issue is resolved in #853
