### ISSUE TITLE
Loading a saved model in PyTorch - Confusion regarding the Weights and Parameters classes

### ISSUE THREAD

**Issue by Linardos** [adap/flower#910]
I'm saving a model according to the guidelines here: https://flower.dev/docs/saving-progress.html

This saves the "aggregated_weights" into an ".npz" file. However, loading this file and its contents into a PyTorch model afterwards for inference is not clear to me. I'm having a bit of a hard time understanding the "aggregated_weights" variable as well as it appears to be a flwr.commons.Parameters class that is not printable (my code hangs whenever I try to print)

So my question is: How can I instead make these "aggregated_weights" into the standard PyTorch state_dict format and save it as ".pt"?

I tried treating the "aggregated_weights" variable like the "parameters variable is treated in this example: https://github.com/adap/flower/blob/main/examples/quickstart_pytorch/client.py#L105-L108

But that didn't work for me. Perhaps this stems from my confusion regarding the flwr.commons.Parameters and Weights classes

**Comment by danieljanes** [comment]
Hi @Linardos, thanks for reaching out. This is a good question that many users might have, so I'll try to answer it with a lot of detail.

`flwr.client.NumPyClient` is a convenience class built on top of `flwr.client.Client`. The difference is that `Client` sends/receives lower-level values that are close to the actual gRPC messages sent over the wire, which in turn means that you have to write a bit more boilerplate code when implementing it. `NumPyClient` is more opinionated (which also means less flexible), but it does a lot of this boilerplate work for you in return.

One example for this boilerplate work is the conversion of model parameters. On the gRPC level, Flower communicates model parameters as byte arrays. To be more precise, Flower uses a gRPC/ProtoBuf message called [`Parameters`](https://github.com/adap/flower/blob/4d95d2627afb27153bfe66d5edff78a905f3f3e8/src/proto/flwr/proto/transport.proto#L24) to represent your model parameters in the following way:

```
message Parameters {
  repeated bytes tensors = 1;
  string tensor_type = 2;
}
```

`repeated` is ProtoBuf-syntax for a list/array-ish data structure. So `Parameters` is a list of byte arrays and a string `tensor_type` that tells someone receiving a `Parameters` object how those byte arrays should be interpreted (after all, the byte arrays could contain anything). The Flower code examples usually serialize a single neural network layer into a byte arrays, so in that case, the `Parameters` object should have a list `tensors` with as many entries as the model has layers.

Coming back to your question, what's the relationship between PyTorch, `NumPyClient`, and `aggregated_weights`?

Since the transport layer uses byte arrays, we have to convert *whatever* model parameters we have into byte arrays. `NumPyClient` is the convenience class that does it for you by asking you to use a list of NumPy `ndarray` objects. So when you return from `fit`, you take the PyTorch `state_dict` and turn it into a list of NumPy `ndarray`s. `NumPyClient` then does a second conversion from this list into a list of byte arrays.

On the server side, the reverse happens: we receive the `Parameters` object with the list of byte arrays, but then we have de-serialize it into a list of NumPy `ndarray`s before we can do any computation on it. This is done inside the `aggregate_fit` method: it converts `Parameters` to `ndarray`s, averages them, and converts them back to `Parameters` ([implementation](https://github.com/adap/flower/blob/4d95d2627afb27153bfe66d5edff78a905f3f3e8/src/py/flwr/server/strategy/fedavg.py#L254)).

Now, to finally answer the question, yes, one can absolutely save the aggregated parameters as a PyTorch `state_dict`. `aggregate_fit` returns a `Parameters` object that has to be transformed into a list of NumPy `ndarray`s, and those have to be transformed into the PyTorch `state_dict` (just the way it's done on the client side). Here's the code:

```python
class SaveModelStrategy(fl.server.strategy.FedAvg):
    def aggregate_fit(
        self,
        rnd: int,
        results: List[Tuple[fl.server.client_proxy.ClientProxy, fl.common.FitRes]],
        failures: List[BaseException],
    ) -> Optional[fl.common.Weights]:
        aggregated_parameters = super().aggregate_fit(rnd, results, failures)
        if aggregated_parameters is not None:
            aggregated_parameters = fl.common.para(aggregated_parameters)
            
            # Convert `Parameters` to `List[np.ndarray]`
            aggregated_weights: List[np.ndarray] = fl.common.parameters_to_weights(aggregated_parameters)
            
            # Load PyTorch model
            net = Net().to(DEVICE)

            # Convert `List[np.ndarray]` to PyTorch`state_dict`
            params_dict = zip(net.state_dict().keys(), aggregated_weights)
            state_dict = OrderedDict({k: torch.tensor(v) for k, v in params_dict})
            net.load_state_dict(state_dict, strict=True)

            # TODO Save PyTorch `state_dict` as `.pt`

        return aggregated_parameters
```

The reason we chose to migrate (almost) all of our API's to use `Parameters` objects is that we want Flower to be serialization-agnostic. In the future, we will make the serialization and deserialization pluggable (i.e., user-configurable through a plugin system).

I also realized that some of the namings in the documentation weren't particularly helpful, so we'll update those to make them easier to follow. When we started the migration to `Parameters`, we tried to use `Weights` as a synonym for `List[np.ndarray]` and `Parameters` for the serialized version thereof, but there are still some historical artifacts where we're not yet following that convention.
