### ISSUE TITLE
Empty distributed metrics in federated evaluation

### ISSUE THREAD

**Issue by SamuBox** [adap/flower#983]
When using the advanced_tensorflow example, and removing the centralized evaluation, I get the desired federated evaluation. But the metrics are empty, and they should show the accuracy. I only get the distributed losses

![image](https://user-images.githubusercontent.com/30962122/147923870-9c8e8f57-f362-4590-a185-6d6812881001.png)

The client is returning the accuracy in the evaluate function

![image](https://user-images.githubusercontent.com/30962122/147923536-4792de4c-68c5-461e-8fc8-b9fd5e9cbb65.png)

Model is compiled with that metric

![image](https://user-images.githubusercontent.com/30962122/147923368-736a6d34-e628-4bf8-ba7a-823297836433.png)

**Comment by danieljanes** [comment]
Hi @SamuBox , thanks for the question! This is expected behaviour, but let me explain: Flower does not automatically aggregate custom metrics (e.g., `{"accuracy": accuracy}`) because it's not always the right thing to do a weighted average and because there are many value types for which there is no sensible default aggregation (e.g., `str`). The dict was intended to be flexible enough to communicate different kinds of custom values back to the server and users might want to use it for things they don't intend to aggregate over the multiple clients (e.g., to log a specific per-client value).

That being said, we understand that the current behaviour can easily confuse users, which is not the user experience we intend to provide :) we're thinking about way that (a) allow users to return custom metrics from the client and automatically aggregate these on the server-side and (b) allow users to return custom values of different types (e.g. `str`) that are not aggregated on the server-side. 

In the meantime, here's the guide that describes how custom metrics can be aggregated: https://flower.dev/docs/saving-progress.html#aggregate-custom-evaluation-results (we could update the `advanced_tensorflow` example to include this).

**Comment by SamuBox** [comment]
@danieljanes Thanks for the detailed answer!

You should definetely include it in the `advanced_tensorflow` , or even better create a `tensorflow_from_centralized_to_federated`

Also this (https://flower.dev/docs/saving-progress.html#aggregate-custom-evaluation-results) example should include all the code, as I can't make it work

Could you post a full example with the fit function? Im getting different errors depending on how I configure the fit function

**Comment by sisco0** [comment]
Could you kindly review if the associated _PR_ makes sense @danieljanes @SamuBox for the centralized version?

**Comment by sisco0** [comment]
Try to clone my _PR_ and run the next commands:

```bash
cd examples/tensorflow_from_centralized_to_federated
poetry install
poetry run run.sh
```

**Comment by SamuBox** [comment]
@sisco0  Thanks for all the work! 

It's works perfect :) 

```
INFO flower 2022-01-07 11:06:12,412 | server.py:172 | FL finished in 402.09212740099974
INFO flower 2022-01-07 11:06:12,413 | app.py:149 | app_fit: losses_distributed [(1, 2.3211318254470825), (2, 2.3191205263137817)]
INFO flower 2022-01-07 11:06:12,413 | app.py:150 | app_fit: metrics_distributed {'accuracy': [(1, 0.10312499850988388), (2, 0.12187499925494194)]}
```
